<!DOCTYPE html>
<html>
<head>
<script src="http://maps.googleapis.com/maps/api/js"></script>
<script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer.js"></script>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobox/src/infobox.js"></script>
<script src="scripts/jquery.csv-0.71.js" charset="utf-8"></script>
<link rel="stylesheet" type="text/css" href="css/style.css" ></style>

</head>

<body>
<div id="googleMap"></div>
<div id="searchDiv">
    <p class="header"><b>Zoek buurten met Buurkracht</b></p>
    <p><input class="input" id="query"  placeholder="Provincie, postcode, plaats of buurt" /><button class="inputButton" onclick="update()">Zoeken</button></p>
</div>
<div id="displayDiv" style="display:none;">
<img src="img/display.jpg" class="display-image" style="width:350px;">
<div class="title">
    <p> Vissersbuurt, Emmerloord  <span class="right"> >  </span> </p>
</div>

<div class="stats">
<p class="number" > 37 </p>
<p class="numberDesc"> deelnemende buren</p>

</div>
<div class="stats last"> 
<p class="number" > 10 </p>
<p class="numberDesc"> acties in de buurt</p>
</div>
</div>

<textarea name="" id="text" rows="8" cols="40" hidden>
    179,"Koekangerveld","Minima natus ipsa nobis. Temporibus quo corrupti optio. Qui aliquam quisquam. Neque eius vel incidunt magnam.","Nihil recusandae amet voluptatibus excepturi eos. Fugit omnis beatae ut nisi. Laudantium dicta soluta. Quos tenetur ab.
    ","Dit is een dummy plaatje ","koekangerveld",1,"koekangerveld",NULL,"2015-07-08 12:31:11","2015-07-21 09:53:50","nieuwe-attractie-efteling-gaat-weer-open-storing.jpg","image/jpeg",74393,"2015-07-21 09:53:50",0,52.7211,6.35418
    180,"Geleerdenbuurt-Noord","Libero sed laborum modi molestiae id sapiente ipsa. Nobis dignissimos ut itaque possimus. Provident autem voluptatem est saepe consequatur occaecati. Omnis neque voluptatem commodi molestias iste debitis. Iure sit eum autem id doloribus.","Dicta ut animi et similique adipisci. Est est molestiae. Occaecati alias veniam omnis consectetur assumenda nisi quos. Vitae consequuntur consectetur est.",NULL,"geleerdenbuurt-noord-berkum",1,"geleerdenbuurt-noord-berkum",NULL,"2015-07-08 12:31:11","2015-07-08 12:31:11",NULL,NULL,NULL,NULL,0,NULL,NULL
    181,"BOEMUC","Officia unde aliquam amet omnis necessitatibus modi sint. Voluptatem corporis nesciunt. Explicabo et aut enim.","Rerum sit vel. Aut velit et ipsa laudantium et temporibus. Nulla qui quo facilis dolorem inventore corporis quis. Vel quam sunt optio. Deserunt dolorum est.",NULL,"boemuc",1,"boemuc",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:28",NULL,NULL,NULL,NULL,0,50.7687,5.02737
    182,"Geleerdenbuurt-Zuid","Aspernatur ut debitis minus ipsam velit non. Molestiae deleniti qui veniam. Voluptas vel eum. Dolor quae quibusdam velit.","Quia libero sit qui quas. Alias rerum reprehenderit deserunt modi. Placeat sed quos dicta consequatur omnis.",NULL,"geleerdenbuurt-zuid-berkum",1,"geleerdenbuurt-zuid-berkum",NULL,"2015-07-08 12:31:11","2015-07-08 12:31:11",NULL,NULL,NULL,NULL,0,NULL,NULL
    183,"Ruwaard - Staatsliedenbuurt","Ut odio consequuntur quod adipisci. Aperiam incidunt quis fuga molestias. Quia eum sunt nam est non. Sed est enim aut. Magni perspiciatis provident doloremque itaque rerum dolore.","Rerum qui ut minus quibusdam porro. Sed libero iusto. Qui officia omnis porro nihil aut.",NULL,"oss",1,"oss",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:30",NULL,NULL,NULL,NULL,0,NULL,5.23217
    184,"Bomenbuurt","Adipisci soluta labore fuga error sint. Eius debitis et natus. Enim et corporis alias reiciendis. Ut tenetur voluptas autem hic molestiae iure. Voluptatem fugiat id in minus velit libero voluptatibus.","Ipsam quae magni autem et velit eos vero. Excepturi ex adipisci officia aliquam blanditiis laborum. Sunt aut quaerat quod enim vitae laborum. Iusto aliquam itaque sit iste assumenda quasi. Nam ut non corporis corrupti facilis facere.",NULL,"berkum",1,"berkum",NULL,"2015-07-08 12:31:11","2015-07-08 12:31:11",NULL,NULL,NULL,NULL,0,NULL,NULL
    185,"Componisten - Natuurkundigenbuurt","Molestiae voluptatibus fugit voluptatem. Praesentium nam ut voluptas molestiae qui excepturi est. Deleniti sit nihil voluptas voluptates magni. Sunt quod atque. Veritatis minima quis sed.","Molestias quam est tempora accusantium sed sunt sint. Porro cum dolore. Velit possimus unde.",NULL,"componistenbuurt",1,"componistenbuurt",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:32",NULL,NULL,NULL,NULL,0,NULL,5.23217
    186,"Loosbroek","Sunt et hic dolorem. Asperiores reprehenderit dolores molestias. Eius blanditiis qui aut.","Ipsa in vero cumque. Ea consequuntur eligendi. Modi adipisci et accusantium similique. Officiis molestiae ipsa. Qui placeat ratione possimus.",NULL,"loosbroek",1,"loosbroek",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:33",NULL,NULL,NULL,NULL,0,51.6797,5.50999
    187,"Hintham-Zuid","Est non consequatur error. Culpa saepe maiores. Quae consequatur facere ducimus ut eum. Magni libero voluptas enim totam.","Tempora asperiores voluptatem omnis neque possimus odit tenetur. Dolores tenetur maxime odit similique velit enim et. Molestiae ad hic temporibus. Omnis aut odit. Aspernatur molestias sit omnis odio.",NULL,"hintham-zuid-rosmalen",1,"hintham-zuid-rosmalen",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:34",NULL,NULL,NULL,NULL,0,NULL,5.23217
    188,"Orthen","Minus asperiores pariatur ab beatae omnis. Facere illum quas autem qui placeat. Sit distinctio officiis.","Nostrum illo quis voluptas aperiam dolores amet in. Cupiditate illum dignissimos molestiae minima cum. Vel qui unde illum iste. Sapiente veniam est omnis. Explicabo veritatis et quam.",NULL,"orthen-den-bosch",1,"orthen-den-bosch",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:36",NULL,NULL,NULL,NULL,0,51.7072,5.30982
    189,"Vasse","Laudantium reiciendis quis. Inventore quasi laboriosam velit vel ut molestiae in. Laboriosam occaecati nihil ipsa. Quos ea aut quis. Dignissimos est praesentium aliquam nihil aut.","Nobis fugit molestiae quaerat in totam. Accusantium est voluptates. Excepturi maiores id sit nesciunt quibusdam officiis eos. Sapiente provident consequatur. Iste dolor quis.",NULL,"vasse",1,"vasse",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:37",NULL,NULL,NULL,NULL,0,52.4335,6.82624
    190,"Elsendorp","Quo magnam sit et. Tempora laboriosam quis. Qui suscipit voluptas earum tempore delectus.","Culpa officiis laudantium qui quia et veniam facere. Est quae earum quo. Occaecati et nulla sed sed mollitia. Fuga temporibus sit et ex.",NULL,"elsendorp",1,"elsendorp",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:38",NULL,NULL,NULL,NULL,0,51.5778,5.77503
    191,"Nudge","Et explicabo modi nulla aut quia sequi. Iusto cupiditate nihil eveniet quo. Voluptatem quis autem itaque soluta ut temporibus aliquam.","Dolore sunt dignissimos quidem inventore maiores nam eos. Aliquid sequi cumque et. Quod praesentium hic error similique enim. Voluptate eum voluptatem dignissimos id harum.",NULL,"nudge",1,"nudge",NULL,"2015-07-08 12:31:11","2015-07-08 12:31:11",NULL,NULL,NULL,NULL,0,NULL,NULL
    192,"Bomen- en Prinsessenbuurt","Quis quod soluta. Delectus id in quia. Doloremque illo vitae fugit. Sequi ut expedita velit corporis. Explicabo repellat fuga nam totam pariatur quam officiis.","Voluptas error laborum sunt quis sit. Culpa vel quo et asperiores. Temporibus qui voluptate rerum dolore sequi aut. Laudantium vitae tempora inventore rerum quibusdam eos.",NULL,"bomen-prinsessenbuurt-dongen",1,"bomen-prinsessenbuurt-dongen",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:40",NULL,NULL,NULL,NULL,0,NULL,5.23217
    193,"Aldlan-West","Est aut et enim qui omnis sit. Aut accusantium suscipit. Perspiciatis sequi dignissimos facere. Qui sunt sit et est.","Sit dolores sunt velit. Praesentium voluptatum reprehenderit tempore omnis. Voluptas quibusdam dicta recusandae.",NULL,"aldlan-west-leeuwarden",1,"aldlan-west-leeuwarden",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:41",NULL,NULL,NULL,NULL,0,53.1847,5.80975
    194,"Aldlan-Oost-Noordzijde","Culpa tempore et aut. Libero vel omnis repellendus molestiae omnis id. Dignissimos omnis numquam commodi officiis qui. Corporis voluptatem porro tempora consequatur. Fuga enim quo unde.","Quo sed repudiandae. Itaque et perferendis. Mollitia nobis nam quo. Laudantium fugit consequatur rerum et. Aliquam quo sed.",NULL,"aldlan-oost-nz-leeuwarden",1,"aldlan-oost-nz-leeuwarden",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:45",NULL,NULL,NULL,NULL,0,53.2012,5.79991
    195,"Aldlan-Oost-Zuidzijde","Neque corrupti sed. Natus saepe et enim amet. Eaque aut excepturi. Quia dolorem aliquid sint iusto autem enim. Ipsam sed ducimus sit sint.","Et quis et eum. Quia deleniti accusantium. Minima quos tempora sapiente ut quod voluptatibus. Voluptatem dolores omnis illo a nobis. Qui et cum ipsum assumenda.",NULL,"aldlan-oost-zz-leeuwarden",1,"aldlan-oost-zz-leeuwarden",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:55",NULL,NULL,NULL,NULL,0,53.2012,5.79991
    196,"Achter de Hoven","Est reiciendis facilis enim temporibus. Et praesentium sit eaque explicabo. Earum ad voluptatem consequatur cum repellat iste accusantium.","Consequatur quisquam assumenda eos et et. Similique laboriosam ipsam qui et porro quibusdam. Sapiente sed officia nostrum qui dolorum maxime voluptatem. Sint et et aperiam laborum in. Quia repudiandae necessitatibus.",NULL,"achter-de-hoven-leeuwarden",1,"achter-de-hoven-leeuwarden",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:56",NULL,NULL,NULL,NULL,0,53.1959,5.81244
    197,"Zuidwest-Smilde","Perferendis quo animi illum est mollitia accusantium accusamus. Repellendus qui velit. Soluta sit laboriosam aliquid magni in illum. Perspiciatis illo quas incidunt qui.","Distinctio porro eaque laborum consequatur qui in. Suscipit commodi vitae error. Exercitationem et sit tenetur aliquid pariatur. Doloremque nostrum consequatur ex ratione. Molestiae et qui eligendi nobis culpa dolorem quo.",NULL,"zuidwest-smilde",1,"zuidwest-smilde",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:56",NULL,NULL,NULL,NULL,0,52.9492,6.44668
    198,"Vroendaal","Aperiam voluptates fugit ullam. Sapiente architecto ipsa occaecati nostrum numquam voluptas. Voluptas inventore non quidem omnis nesciunt quos fuga.","Aut accusantium rem sit ex vero fugit. Molestiae provident voluptas aut molestias. Rerum quis voluptatem consequatur ut tempore. Voluptatem ducimus beatae.",NULL,"vroendaal-maastricht",1,"vroendaal-maastricht",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:57",NULL,NULL,NULL,NULL,0,50.8271,5.73895
    199,"Klein Brabant","Reprehenderit ut adipisci doloremque rerum in. Dolor inventore eius accusantium labore voluptas illum. Cumque aut et incidunt suscipit in. Consequatur culpa sed nihil eligendi illo sunt quis. Consequuntur eos aut quaerat laboriosam.","Aliquid maxime velit cumque corrupti sit. Ea vel cumque neque. Culpa vero adipisci veritatis. Itaque pariatur velit recusandae sequi enim consectetur dolores.",NULL,"klein-brabant-vught",1,"klein-brabant-vught",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:58",NULL,NULL,NULL,NULL,0,51.6371,5.2926
    200,"Den Dungen-Oost","Impedit veniam cum dolorum. Est ut tempore. Illum modi quia eaque. Quaerat debitis deserunt iure totam. Voluptatem voluptas labore dolores repellendus est dolor.","Possimus dicta rerum ut est. Maiores consequuntur dolorem et. Ipsa voluptatibus qui. Tempora ea pariatur officiis aspernatur praesentium.",NULL,"den-dungen-oost",1,"den-dungen-oost",NULL,"2015-07-08 12:31:11","2015-07-20 08:25:59",NULL,NULL,NULL,NULL,0,NULL,5.23217
    201,"Heyencamp","Ratione tempore sit est optio quod et. Consequuntur tempore adipisci similique quia. Enim quas numquam tenetur sapiente dolores.","Vero tenetur minima voluptatem et tempora commodi ut. Repellendus nemo amet qui ut assumenda non. Consequatur suscipit est. Rem nobis omnis dolor. Nobis cumque eveniet.",NULL,"heyencamp-reuver",1,"heyencamp-reuver",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:00",NULL,NULL,NULL,NULL,0,51.2828,6.08904
    202,"Bitswijk-Noord","Autem deleniti odit eius ut consequatur. Distinctio molestiae illum. Tenetur tempora et voluptatum consequatur dolores. Blanditiis quos et est.","In rerum consequatur molestiae. Porro consequuntur quaerat numquam qui qui harum explicabo. Porro quod natus accusamus consequuntur est. Aut minus quae quas. Ex velit dolores non similique sunt.",NULL,"bitswijk-noord-uden",1,"bitswijk-noord-uden",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:00",NULL,NULL,NULL,NULL,0,NULL,5.23217
    203,"Bitswijk-Oost","Ea ut dolor vitae voluptas. Voluptatem commodi dignissimos error veniam nam. Culpa illo rerum eum quia. Commodi fugit et nobis. Sit ea optio doloremque itaque.","Delectus iste aspernatur voluptates hic aut praesentium. Occaecati quaerat sapiente nobis atque maiores. Nam et inventore consequatur illum.",NULL,"bitswijk-oost-uden",1,"bitswijk-oost-uden",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:08",NULL,NULL,NULL,NULL,0,NULL,5.23217
    204,"Bitswijk-West","Non non ea quibusdam eveniet veritatis nesciunt porro. Et ut consectetur beatae impedit sequi dicta. Quia est in ullam velit. Rem vel cum numquam doloribus voluptas.","Omnis sit aut. Corrupti vel asperiores sed voluptatem accusamus laboriosam provident. Reprehenderit molestiae tempora magni.",NULL,"bitswijk-west-uden",1,"bitswijk-west-uden",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:13",NULL,NULL,NULL,NULL,0,51.6689,5.60906
    205,"Noorderpark omgeving Venestraat","Deleniti quam eos doloribus accusamus minima harum. Provident at et perferendis voluptas quia occaecati vel. Deserunt consequuntur quis. Dolores unde quibusdam qui aspernatur pariatur.","Et quia voluptatem exercitationem illo qui. Voluptate excepturi numquam placeat aut. Consequatur eligendi voluptatibus explicabo consectetur laudantium consequatur voluptas. Totam provident est sed laboriosam distinctio expedita harum. Accusamus magni et voluptates qui dolores aspernatur libero.",NULL,"noorderpark-omgeving-venestraat-assen",1,"noorderpark-omgeving-venestraat-assen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:14",NULL,NULL,NULL,NULL,0,52.9928,6.56423
    206,"Nijveenschemond","Cupiditate perferendis libero autem. Odio dolor et cumque similique. Soluta et dicta debitis voluptatem laboriosam provident architecto. Odit praesentium culpa dolorum sed cumque.","Et fugit hic quia. Reprehenderit distinctio ipsam molestiae doloribus iste. Quaerat non omnis et sequi placeat unde enim. Sunt dolor est temporibus et. Quia ut illum ipsam rem aut.",NULL,"gasselternijveenschemond",1,"gasselternijveenschemond",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:15",NULL,NULL,NULL,NULL,0,52.995,6.8974
    207,"Oosterveld","Aliquam atque placeat itaque quia sint. Qui et eaque laudantium nesciunt quibusdam consequatur. Suscipit quo nostrum laudantium voluptate harum quas temporibus.","Autem accusantium recusandae quia dolor. Non maiores est veniam nobis. In quia ut saepe corporis labore. Vitae et qui quam. Non soluta at et assumenda.",NULL,"oosterveld-rolde",1,"oosterveld-rolde",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:15",NULL,NULL,NULL,NULL,0,52.9801,6.65505
    208,"Nieuw-Dordrecht","Suscipit nemo esse consectetur repudiandae nihil commodi hic. Neque natus sunt voluptatem exercitationem quia dolor. Sed quos nobis optio ducimus neque omnis rerum. Dolorem ducimus aspernatur molestiae ea itaque.","Corrupti accusantium veritatis. Ut laborum labore rerum itaque. Itaque odit sunt dolore. Dolore iusto ut sapiente et non.",NULL,"nieuw-dordrecht",1,"nieuw-dordrecht",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:16",NULL,NULL,NULL,NULL,0,52.7372,6.98299
    209,"Hoonhorst","Tempore laboriosam enim magni rem et harum. Recusandae alias perferendis dolor repudiandae nemo. Officia eum voluptatem. Sunt nihil perspiciatis quis. Voluptatem vero sed illum tempora ipsa.","Similique eius vel voluptatem. Et blanditiis modi iste molestias officiis. Nesciunt blanditiis et. Eaque atque delectus doloribus eos expedita.",NULL,"hoonhorst",1,"hoonhorst",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:17",NULL,NULL,NULL,NULL,0,52.4844,6.22935
    210,"Kastelenbuurt","Accusantium velit quidem quam dolores harum omnis. Nam et doloremque nemo velit eos. Consectetur dolore non. Debitis incidunt ut.","Cupiditate voluptas minus rerum commodi id voluptatem. Itaque et pariatur unde dolorem reprehenderit cum. Rem aliquid magnam laboriosam.",NULL,"kastelenbuurt-oosterhout",1,"kastelenbuurt-oosterhout",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:17",NULL,NULL,NULL,NULL,0,NULL,5.23217
    211,"Prinsenbeek","Cumque pariatur magnam voluptatem. Aspernatur praesentium accusantium est. Necessitatibus et recusandae quis dolor.","Enim exercitationem aliquid non cumque quibusdam facilis eveniet. A corporis incidunt quos. Corporis delectus dolor commodi eum natus itaque neque. Nam consectetur maiores facere non in magnam.",NULL,"prinsenbeek",1,"prinsenbeek",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:18",NULL,NULL,NULL,NULL,0,51.5967,4.71855
    212,"Vrijhoeve","Exercitationem accusantium numquam qui. Voluptatem minus et expedita corrupti dolorum et sapiente. Perspiciatis ut consectetur. Autem et facere porro quisquam quidem. Consequuntur tenetur ex iure sed.","Placeat rerum aut earum eos reiciendis consequatur. Occaecati molestiae est. Quo quia dolor et. Ut natus et et.",NULL,"vrijhoeve-sprang-capelle",1,"vrijhoeve-sprang-capelle",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:21",NULL,NULL,NULL,NULL,0,51.6758,5.01715
    213,"Rivierenbuurt Parkweg IJsselstraat","Qui distinctio pariatur. Minus animi quia. Temporibus perspiciatis eveniet quia. Saepe ut quia omnis maxime voluptatibus iusto. Molestias quis sed nihil explicabo saepe ut.","Ea maxime fuga laborum rem et animi magni. Voluptate dolor minima sit atque repellendus. Voluptas non ullam aliquam temporibus aliquid. Placeat aliquam occaecati reprehenderit alias dolorum id eaque. Quis amet et saepe quis repellendus ut.",NULL,"rivierenbuurt-parkweg-ijsselstraat-groningen",1,"rivierenbuurt-parkweg-ijsselstraat-groningen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:22",NULL,NULL,NULL,NULL,0,53.2078,6.56302
    214,"Princenhage-Ambachtenbuurt","Ipsum quaerat explicabo quae voluptatem. Eos placeat odio qui. Corporis provident quasi. Consequatur illum ipsam sed aut excepturi rerum quam.","Consectetur adipisci dignissimos expedita omnis. Quidem est perferendis qui aut enim et. Consectetur aut nesciunt dolorem eum animi. Nesciunt amet culpa nihil earum aut.",NULL,"ambachtenbuurt-princenhage-breda",1,"ambachtenbuurt-princenhage-breda",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:23",NULL,NULL,NULL,NULL,0,NULL,5.23217
    215,"Ulvenhout-Zuidwest","Cupiditate blanditiis amet atque autem consectetur tenetur vel. Aut dolores facere velit aut consequatur earum voluptatem. Facilis delectus laudantium et excepturi distinctio. Voluptas impedit illum quia quis et et.","Libero qui quia. Non quod adipisci quos. Porro quia aspernatur accusantium similique in.",NULL,"ulvenhout-zuidwest",1,"ulvenhout-zuidwest",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:24",NULL,NULL,NULL,NULL,0,NULL,5.23217
    216,"Marsdijk","Magni quia eum consequatur dolores nihil earum. Maxime eligendi aut quis sapiente ea culpa reiciendis. Saepe dicta quaerat omnis accusamus facilis. Velit est quia. Nihil odit iure eum beatae.","Iure accusamus ut sint et voluptas et. Animi unde totam odit. Deserunt ut explicabo quia aut necessitatibus vero.",NULL,"marsdijk-assen",1,"marsdijk-assen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:25",NULL,NULL,NULL,NULL,0,53.0184,6.5796
    217,"Benzenrade-De Kommert","Ut architecto neque ut repudiandae harum hic ut. Laboriosam ipsa harum. Aut voluptas expedita ducimus veniam.","Unde harum dolorem assumenda. Occaecati labore fugiat reiciendis fuga dolore quasi ab. Iusto quaerat quia repellendus et. Ipsum voluptas dolorum quod sunt. Sint dignissimos quibusdam sit eum possimus.",NULL,"benzenrade-de-kommert-heerlen",1,"benzenrade-de-kommert-heerlen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:25",NULL,NULL,NULL,NULL,0,50.8907,5.97584
    218,"Albano","Sunt praesentium perferendis. Est nesciunt incidunt occaecati. Exercitationem et perspiciatis laboriosam eum culpa sint dicta. Sed temporibus doloremque aperiam illum sed. Molestias ut quo.","Hic quidem tempore. Tenetur est magnam iusto nulla laborum. Sint minus at. Quaerat labore recusandae illo fugit fugiat eum distinctio.",NULL,"albano-oudenbosch",1,"albano-oudenbosch",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:26",NULL,NULL,NULL,NULL,0,51.5842,4.5345
    219,"Rivierenbuurt Fongersplaats","Veniam non iste. Delectus optio molestias facere nihil error blanditiis. Ad a odit inventore aut accusamus. Et officiis accusamus. Id voluptas aliquid eum atque eum eaque.","Temporibus quam et rerum omnis. Fuga error dicta sequi ipsum ratione. Ut cum consectetur enim. Atque distinctio iure natus.",NULL,"rivierenbuurt-fongersplaats-groningen",1,"rivierenbuurt-fongersplaats-groningen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:27",NULL,NULL,NULL,NULL,0,53.2077,6.57201
    220,"Sint Agatha","Dicta temporibus reiciendis laudantium. Molestiae voluptatem aliquid. Quaerat est quos culpa distinctio odit et.","Maxime officia quod sed aut et quia. Cupiditate non fugit velit. Rerum voluptatem quis commodi. Sit autem odit.",NULL,"sint-agatha",1,"sint-agatha",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:28",NULL,NULL,NULL,NULL,0,51.701,5.87977
    221,"Made-Noord","Ipsam commodi ad tenetur qui voluptas illo. Facere ut ipsum modi quae consectetur molestias dicta. Deleniti aut porro id aut quia quam repellendus.","Veritatis hic repellendus. Sit quis architecto nulla dolor voluptate nam. Impedit porro et at deleniti consequatur.",NULL,"made-noord",1,"made-noord",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:28",NULL,NULL,NULL,NULL,0,51.4827,5.23217
    222,"Besoyen-West","Culpa pariatur quia non hic est ea. Porro doloribus itaque odio et alias atque voluptate. Necessitatibus nobis commodi ut est ut. Nesciunt doloremque aut suscipit. Dolor aut rem totam.","Enim vel vero. Quasi minima rerum. Pariatur autem voluptatem ut id dolorem. Eius autem quas et exercitationem. Officia voluptate et minima ut qui.",NULL,"besoyen-west-waalwijk",1,"besoyen-west-waalwijk",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:29",NULL,NULL,NULL,NULL,0,51.6888,5.0538
    223,"Nieuw-Weerdinge","Velit quisquam quo adipisci et qui qui soluta. Minima omnis ea accusamus. Aut accusantium inventore. Suscipit eum asperiores.","Dolorem fuga libero. Ea sint sapiente quod optio fugiat eaque veniam. Sapiente et asperiores. Animi laboriosam esse quisquam qui quidem occaecati vitae.",NULL,"nieuw-weerdinge",1,"nieuw-weerdinge",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:30",NULL,NULL,NULL,NULL,0,52.8184,6.91796
    224,"Zeeheldenbuurt omgeving Van Brakelplein","Neque beatae qui. Corporis iste aliquid. Incidunt iste voluptates et.","Deserunt beatae iusto amet. Rerum qui maxime aperiam veritatis. Sit qui quae repellat.",NULL,"zeeheldenbuurt-omgeving-van-brakelplein-groningen",1,"zeeheldenbuurt-omgeving-van-brakelplein-groningen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:31",NULL,NULL,NULL,NULL,0,53.2119,6.55078
    225,"Het Ven","Qui nihil sequi suscipit voluptatem. Sunt ad mollitia dolorum non aut sit et. Eaque iusto deleniti quidem inventore quae. Quia voluptatem officiis laboriosam mollitia illo est consequatur. Repellendus doloribus rerum nam.","Omnis accusamus non cumque velit velit dolorem. Sit autem harum reiciendis ipsa ea quis. Totam excepturi id.",NULL,"het-ven-venlo",1,"het-ven-venlo",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:31",NULL,NULL,NULL,NULL,0,51.386,6.19453
    226,"De Wijert-Zuid","Quis temporibus iure quibusdam id. Labore ipsum ut quo. Doloribus blanditiis voluptates repellendus dolor voluptate id.","Voluptas quasi magnam vel. Amet laborum distinctio esse. Illum recusandae nihil possimus et necessitatibus.",NULL,"de-wijert-zuid-groningen",1,"de-wijert-zuid-groningen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:32",NULL,NULL,NULL,NULL,0,53.1894,6.57092
    227,"Zijldijk","Magni veniam in nam sapiente recusandae et. Cum omnis sed amet iusto consequatur. Magni sit et architecto ut accusamus. Earum qui et aut totam aut. Rem ipsa quia sunt dolore.","Facere voluptatum in fugit corporis adipisci laudantium. Aut laudantium est. Eum libero assumenda ut. Sit rem temporibus doloribus quam.",NULL,"zijldijk",1,"zijldijk",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:33",NULL,NULL,NULL,NULL,0,53.394,6.75701
    228,"Enexisbuurt","Eius voluptatum odio necessitatibus sit repellendus. Soluta dicta est. Error et iure. Quis aspernatur doloremque doloribus. Sit non aliquam deserunt suscipit aut.","Quia minima optio dolor reiciendis aspernatur earum natus. Quas provident cupiditate voluptatem ut ut possimus. In quas quo odio nesciunt. Aut et consequuntur consectetur voluptas soluta. Omnis aspernatur laborum.",NULL,"enexisbuurt",1,"enexisbuurt",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:34",NULL,NULL,NULL,NULL,0,51.4827,5.23217
    229,"Heesch-Noord","Vitae ab aut id dolores aut harum earum. Saepe velit quasi. Rem non enim. Nulla dignissimos nisi. Ex omnis ullam repudiandae.","Debitis id est sapiente. Voluptas maxime soluta dolorum laudantium quia. Non dolorem perferendis nihil dignissimos quia ea. Qui fuga excepturi occaecati dolores necessitatibus voluptas asperiores. Laudantium accusamus veritatis dolore.",NULL,"heesch-noord",1,"heesch-noord",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:34",NULL,NULL,NULL,NULL,0,51.4827,5.23217
    230,"Fatima","Repudiandae impedit labore ipsam quo tempora. Sed quia id voluptas molestias. Perferendis consectetur facere.","Eum eos quis sed distinctio voluptatem veritatis enim. Quae laboriosam dolorem ipsa fuga. Ut eligendi earum a.",NULL,"fatima-tilburg",1,"fatima-tilburg",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:35",NULL,NULL,NULL,NULL,0,51.5501,5.10041
    231,"Itteren","Est saepe dolores nihil. Quaerat facere et autem sit rerum qui. Unde in molestiae.","Tempore ex iusto saepe dolores accusantium. Vel maiores nam similique suscipit necessitatibus officia. Eveniet voluptate distinctio.",NULL,"itteren",1,"itteren",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:36",NULL,NULL,NULL,NULL,0,50.8924,5.70837
    232,"Oranjestraat en omgeving","Beatae minima quos facere excepturi cupiditate. Dolores qui impedit quia maxime sed ex. Voluptas aliquid in amet dolorem rerum repudiandae. Error veniam molestiae harum officia.","Magnam corporis neque labore et. Fugiat quia pariatur est. Maxime sit nesciunt temporibus autem. Aspernatur nihil autem dolor sed nulla eos quia. Consequatur enim magnam quos dolorem.",NULL,"oranjestraat-en-omgeving-gilze",1,"oranjestraat-en-omgeving-gilze",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:36",NULL,NULL,NULL,NULL,0,51.4827,5.23217
    233,"De Lariks-Zuid","Natus consectetur quaerat minus possimus. Ipsam a dicta inventore dolores vero voluptatem. Laborum libero recusandae repellat praesentium ullam. Id eaque occaecati qui ipsam iste voluptatibus aperiam. Ratione vitae praesentium.","Eos quis quos quidem hic deleniti quis. Voluptates eveniet ea velit dolor neque. Quae esse soluta perferendis. Eius id quibusdam architecto consequatur.",NULL,"de-lariks-zuid-assen",1,"de-lariks-zuid-assen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:37",NULL,NULL,NULL,NULL,0,52.9928,6.56423
    234,"America","Nesciunt omnis ipsam harum inventore repellat dolorem natus. Qui sint sit id at. Sit minima rerum et. Qui voluptas pariatur quia facilis.","Soluta esse nam. Vero voluptatem culpa sed dolor. Et dolorum ea. Cum quam quaerat rerum numquam qui et.",NULL,"america",1,"america",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:38",NULL,NULL,NULL,NULL,0,51.4376,5.94706
    235,"Ulrum","Eum temporibus aut non. Saepe veritatis quos. Aliquam nisi sit dolores deleniti eum maxime eos.","Rem aliquid voluptatem iure quia est. Sapiente accusantium eius nulla. Sit vel laudantium. Ut expedita minima eum. Soluta molestiae alias maxime.",NULL,"ulrum",1,"ulrum",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:39",NULL,NULL,NULL,NULL,0,53.3596,6.33796
    236,"West 1","Ex et voluptate et voluptatem. Magni culpa qui quaerat illum libero qui eveniet. Esse animi qui.","Tempora officiis officia atque voluptatem repellendus fugiat vel. Corrupti consequatur qui aliquam at accusantium. Molestias possimus dolorum. Praesentium sequi voluptatibus aliquam.",NULL,"west-1-dongen",1,"west-1-dongen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:39",NULL,NULL,NULL,NULL,0,51.536,4.44477
    237,"Ekenrooi","Ut odit doloribus sint libero inventore autem dignissimos. Quis eaque qui nostrum. Quos aut fugit a aut non.","Maxime dignissimos recusandae vero nisi aut sint et. Distinctio repudiandae aut. Nulla cum earum sed.",NULL,"ekenrooi-aalst",1,"ekenrooi-aalst",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:40",NULL,NULL,NULL,NULL,0,51.3985,5.48208
    238,"Rivierenbuurt Achterweg","Reprehenderit natus praesentium mollitia accusantium. Ducimus rerum id vitae est deserunt maiores. Quia nam voluptatem qui. Et reprehenderit dicta expedita quo ab voluptatibus itaque. Id cumque dolorem molestiae.","Occaecati et id et facere esse. Blanditiis labore libero et. Facere sunt expedita illum quaerat. Architecto aliquam possimus explicabo occaecati. Minima alias maiores nam.",NULL,"rivierenbuurt-achterweg-groningen",1,"rivierenbuurt-achterweg-groningen",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:41",NULL,NULL,NULL,NULL,0,53.2097,6.56767
    239,"De Mortel","Vitae in sunt. Expedita dolorum voluptate. Est suscipit qui magni nemo distinctio sint. Inventore dolores aperiam quod consequuntur cumque. Et vitae ab eos id.","Esse nemo ullam velit doloremque et voluptatibus id. Dolores quibusdam sit dolorum necessitatibus. Numquam occaecati voluptatibus.",NULL,"de-mortel",1,"de-mortel",NULL,"2015-07-08 12:31:11","2015-07-20 08:26:42",NULL,NULL,NULL,NULL,0,51.6123,5.15791
    240,"Reitdiep","Fuga molestiae tenetur nam. Libero explicabo magni iste. Non autem dolores praesentium quae. Amet dolorum iste et quos omnis.","Cum illum sequi rerum. Velit earum molestias accusamus voluptatem consectetur accusantium aliquid. Sapiente laboriosam vel.",NULL,"reitdiep-groningen",1,"reitdiep-groningen",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:08",NULL,NULL,NULL,NULL,0,53.2435,6.52057
    241,"Hoogeloon","In iure saepe rerum consequatur labore qui et. Asperiores repellat vel dolore est labore. Odit consequatur a ut. Commodi mollitia quod tempore et officia. Minus nulla debitis ab sed quia.","Dolores porro iste est tempora facere ut. Voluptas ut voluptatem accusamus. Esse sunt atque.",NULL,"hoogeloon",1,"hoogeloon",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:09",NULL,NULL,NULL,NULL,0,51.398,5.26666
    242,"Baarloseweg","Id voluptas qui velit perferendis occaecati excepturi. Fuga et quo occaecati atque. Inventore ullam rem et assumenda temporibus. Exercitationem aut nostrum vero. Mollitia aut ipsum aut reprehenderit dolorum voluptatem quia.","Eos aut sed reiciendis consectetur. Et ut impedit. Similique perspiciatis vel qui nulla qui et. Iusto dolorum aliquid aut voluptatibus cupiditate.",NULL,"baarloseweg-helden",1,"baarloseweg-helden",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:09",NULL,NULL,NULL,NULL,0,51.3287,6.02097
    243,"De Buurtjes","Porro veniam incidunt. Id sed harum labore dolor nisi. Omnis dicta tempora.","A laudantium aut molestiae incidunt odio. Rerum consequatur dolores sit dolor ipsam inventore perferendis. Aut sequi unde voluptatum deserunt voluptas. Vero sapiente recusandae soluta ut.",NULL,"de-buurtjes-oss",1,"de-buurtjes-oss",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:10",NULL,NULL,NULL,NULL,0,51.4827,5.23217
    244,"Sportpark","Labore reprehenderit eos cumque illo repellat consequatur non. Dignissimos voluptate earum. Sed quis atque architecto et placeat laudantium.","Aut aut quos. Quas velit ut ex natus impedit. Qui omnis ut id. Quam cum dolor.",NULL,"sportpark-breda",1,"sportpark-breda",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:11",NULL,NULL,NULL,NULL,0,51.5831,4.79371
    245,"Vonderkwartier","Maiores sed odio officia qui eos. Minus dolorem voluptates repellendus dolorum similique placeat minima. Enim incidunt eius aliquam suscipit nesciunt. Veniam ut quis ratione consequatur.","Possimus magnam laborum cupiditate aspernatur. Officiis consequatur voluptatem. Ad velit et. Autem earum aut voluptas velit. Cupiditate totam sed reiciendis.",NULL,"vonderkwartier-eindhoven",1,"vonderkwartier-eindhoven",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:11",NULL,NULL,NULL,NULL,0,51.442,5.43966
    246,"Diepenveen-Noord","Exercitationem deserunt maxime laudantium doloribus possimus. Possimus a adipisci quas voluptatem ipsam perspiciatis. Est et sit autem ut.","Voluptatum dolorem ut. Placeat voluptas mollitia sit ut odit sed. Sed sequi ipsum ducimus.",NULL,"diepenveen-noord",1,"diepenveen-noord",NULL,"2015-07-08 12:31:11","2015-07-08 12:31:11",NULL,NULL,NULL,NULL,0,NULL,NULL
    247,"De Kuil","Illo totam expedita ut error quis est autem. Excepturi numquam modi adipisci dignissimos inventore officia. Quia magnam molestias perferendis voluptates impedit illum pariatur. Quo aut omnis qui architecto assumenda. Omnis pariatur voluptas consequuntur placeat qui.","Aut autem quas iste ut in natus et. Eos sunt consequatur. Exercitationem voluptas esse architecto.",NULL,"de-kuil-udenhout",1,"de-kuil-udenhout",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:13",NULL,NULL,NULL,NULL,0,51.6055,5.13184
    248,"Sweensplein en omgeving","Quas rem nihil corporis. Neque aut excepturi voluptate. Sint officiis voluptates.","Et quia corporis sit. Sed quisquam vel natus dolores et voluptatibus incidunt. Laudantium vel molestias quia sapiente minima magni. Vel est est.",NULL,"sweensplein-en-omgeving-rijen",1,"sweensplein-en-omgeving-rijen",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:14",NULL,NULL,NULL,NULL,0,51.4827,5.23217
    249,"Bolhaar","Deserunt expedita ex accusamus quaerat sapiente voluptas amet. Non nam sint explicabo maiores praesentium commodi. Est veniam occaecati voluptates.","Animi vero porro perspiciatis vitae vel. Qui et non quo facere voluptas aliquam impedit. Rem atque ipsum doloremque dolorem. Veritatis fugit dolorum ut eveniet non.",NULL,"bolhaar-enschede",1,"bolhaar-enschede",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:14",NULL,NULL,NULL,NULL,0,52.2393,6.87899
    250,"Nieuw-Roden en omgeving","Perspiciatis non ut minima dolore et. Recusandae est corporis incidunt laborum. Quidem voluptatum ullam ratione.","Illum temporibus beatae dolore nihil quia perspiciatis. Laudantium alias illum sint eveniet est. Omnis quaerat est expedita quasi occaecati. Non praesentium odio.",NULL,"nieuw-roden-en-omgeving",1,"nieuw-roden-en-omgeving",NULL,"2015-07-08 12:31:11","2015-07-08 12:31:11",NULL,NULL,NULL,NULL,0,NULL,NULL
    251,"Noorderplantsoenbuurt","Ipsum modi occaecati. Ipsum eveniet voluptatibus perspiciatis id. Et odio et consequuntur veritatis pariatur ea beatae.","Expedita et odit et excepturi sunt. Et magni et dolorum numquam ducimus dignissimos ea. Et tempora quis.",NULL,"noorderplantsoenbuurt-groningen",1,"noorderplantsoenbuurt-groningen",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:16",NULL,NULL,NULL,NULL,0,53.2194,6.5665
    252,"Buurtschappen Slenaken","Sapiente quia sunt nihil eveniet qui molestiae. Sapiente est aliquam sit ut eos vero. Non quos natus consequatur est. Ratione explicabo qui voluptates vel numquam harum aut. Voluptatibus quis laboriosam quae voluptas itaque fuga totam.","Perferendis aperiam officia iste at. Corporis illo sit tempore animi laboriosam. Ex explicabo asperiores velit et ipsa nulla id. Repudiandae occaecati quaerat delectus dolorem distinctio. Non autem reprehenderit iste consequuntur magnam nihil voluptas.",NULL,"buurtschappen-slenaken",1,"buurtschappen-slenaken",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:16",NULL,NULL,NULL,NULL,0,50.7687,5.86135
    253,"Roerzicht","Dignissimos et sed at itaque vitae velit. Earum dolores incidunt. Sunt nulla dignissimos. Est ut voluptas illum est.","Facilis sunt nulla laudantium repudiandae pariatur. Neque est eius. Qui autem inventore illum dolor.",NULL,"roerzicht-roermond",1,"roerzicht-roermond",NULL,"2015-07-08 12:31:11","2015-07-20 08:27:17",NULL,NULL,NULL,NULL,0,51.187,5.98592
    254,"Roer-Zuid","Laboriosam nobis ut. Fugit consequatur id. Laborum eos fugit doloremque perferendis.","Sint iste totam veritatis culpa fugit. Labore adipisci error qui porro molestias. Earum et et cumque sint debitis consequatur veritatis.",NULL,"roer-zuid-roermond",1,"roer-zuid-roermond",NULL,"2015-07-08 12:31:11","2015-07-20 08:29:19",NULL,NULL,NULL,NULL,0,51.1913,5.98777
    255,"Nieuw Lotbroek","Exercitationem molestias facere nobis. Enim qui est quia eius quos labore. Temporibus autem tempora cum accusantium earum. Et magnam illo ut eaque dolores.","Et earum illo sapiente. Consequatur veniam aut. Ullam provident saepe vel molestiae.",NULL,"nieuw-lotbroek-hoensbroek",1,"nieuw-lotbroek-hoensbroek",NULL,"2015-07-08 12:31:11","2015-07-20 08:29:19",NULL,NULL,NULL,NULL,0,50.9121,5.92832
    256,"Handel","Ut hic sed quae. Quia et consequuntur aut ea. Rerum delectus sunt ullam. Perferendis quae quia explicabo aperiam autem aut quo.","Corporis officiis soluta tenetur aut. Magni eius nemo veritatis cum. Assumenda rerum odit id.",NULL,"handel",1,"handel",NULL,"2015-07-08 12:31:11","2015-07-20 08:29:21",NULL,NULL,NULL,NULL,0,51.5733,5.70928
    257,"Aldlan","Autem blanditiis ut nesciunt ipsa voluptas maiores sit. Quia ab rerum. Eveniet et ut qui aut recusandae. Est illo voluptatem fuga accusantium.","Maiores amet facere eum asperiores. Nesciunt dolor in. Reiciendis qui odit et magni ut veritatis sed. Odit qui vel optio. Sint sit dicta et magni.",NULL,"aldlan-leeuwarden",1,"aldlan-leeuwarden",NULL,"2015-07-08 12:31:11","2015-07-20 08:29:21",NULL,NULL,NULL,NULL,0,53.1935,5.8248
    258,"Grobbendonck","Laudantium impedit voluptatem rem laborum velit minima quam. A optio qui sit unde consequatur accusantium id. Et consequatur sint quae.","Nulla ea aut sit enim quia dolorem. Impedit repudiandae voluptatem. Corporis eveniet officia eos et et. Quisquam optio sed magni dolores explicabo sit tenetur. Aperiam occaecati ut temporibus cum.",NULL,"grobbendonck-goirle",1,"grobbendonck-goirle",NULL,"2015-07-08 12:31:11","2015-07-20 08:29:22",NULL,NULL,NULL,NULL,0,51.5269,5.07027
    259,"Pleijendal","Quasi natus possimus et unde voluptatem doloremque nihil. Dicta debitis ut ut molestiae libero sed minus. Et cum sit enim animi quis quidem. Dolorum vero omnis est minima nisi facere. Eos ut distinctio qui.","A et quidem delectus sint ab nemo. Sapiente maiores excepturi. Ut autem aut.",NULL,"pleijendal-dalfsen",1,"pleijendal-dalfsen",NULL,"2015-07-08 12:31:11","2015-07-20 08:29:23",NULL,NULL,NULL,NULL,0,52.5069,6.25731
    260,"Zandberg","Delectus facilis officiis fuga nihil. Nihil tenetur eligendi aliquid corrupti laboriosam voluptatem veritatis. Distinctio fugit et aut laborum commodi debitis alias. Quas ipsa iure voluptate enim ut. Reiciendis facilis ut est voluptatibus libero omnis.","Fugit et est atque placeat eos accusamus voluptatem. Fugit repellat qui et dolore maxime repudiandae. Ea et consequatur est voluptas voluptate delectus facere.",NULL,"zandberg-breda",1,"zandberg-breda",NULL,"2015-07-08 12:31:11","2015-07-20 08:29:24",NULL,NULL,NULL,NULL,0,51.5769,4.78306
    261,"Beers","Doloribus ducimus quam. Placeat iste illo ut nesciunt eos quaerat. Doloribus officiis quis sunt vero doloremque.","Aspernatur sunt omnis porro eligendi. Voluptas dolor velit omnis sint impedit officia. Totam consectetur quaerat adipisci esse mollitia qui. Dolore quo animi nihil.",NULL,"beers",1,"beers",NULL,"2015-07-08 12:31:11","2015-07-20 08:29:25",NULL,NULL,NULL,NULL,0,51.7248,5.8281
    262,"Groeningen","Quae dolorem unde. Tenetur quam numquam laudantium. Cumque ad doloremque. Temporibus qui qui perspiciatis natus esse voluptas. Ex laboriosam sint explicabo officiis quam ratione repudiandae.","Suscipit consequatur voluptas fugit est. Facilis minima laborum nihil. Aut et totam dicta.",NULL,"groeningen",1,"groeningen",NULL,"2015-07-08 12:31:12","2015-07-20 08:29:25",NULL,NULL,NULL,NULL,0,51.6093,5.99647
    263,"Hart van Clumme","Debitis nisi sapiente. Labore eos fugit velit. Deserunt dolores facilis consequatur magni. Magnam a accusantium fugit hic vitae est.","Saepe qui asperiores non. Dolorem necessitatibus et quia alias eligendi aut. Fugiat consectetur ut et. Quae facere sed.",NULL,"hart-van-clumme-klimmen",1,"hart-van-clumme-klimmen",NULL,"2015-07-08 12:31:12","2015-07-08 12:31:12",NULL,NULL,NULL,NULL,0,NULL,NULL
    264,"Kortland","Repellendus dolor dolore ut porro et. Magni accusamus ipsam laborum sunt placeat rerum. Pariatur voluptatem sunt. Reprehenderit qui architecto. Molestiae dignissimos est hic.","Illum quis voluptatibus eaque aperiam voluptatem. In ut dolorum aspernatur cumque beatae consequatur. A fuga vero error voluptatum. Nesciunt rem qui. Dicta inventore molestiae et tempora ipsum.",NULL,"kortland-peize",1,"kortland-peize",NULL,"2015-07-08 12:31:12","2015-07-08 12:31:12",NULL,NULL,NULL,NULL,0,NULL,NULL
    265,"Stations-Oranjebuurt","Fugit dignissimos repellat. Ipsam qui ut excepturi omnis aut voluptas voluptatem. Non maxime voluptatum laboriosam. At a omnis voluptatem. Voluptate ut est facere tempore recusandae.","Ex consequatur eum aut saepe. Magnam aspernatur quisquam libero. Et rem praesentium. Nihil explicabo et. Iusto quam blanditiis quia corrupti libero.
    ","Stations-Oranjebuurt","stations-oranjebuurt-deurne",1,"stations-oranjebuurt-deurne",NULL,"2015-07-08 12:31:12","2015-07-20 08:29:27","home-hero_oosterhout.jpg","image/jpeg",684862,"2015-07-08 12:37:39",1,NULL,5.23217
    266,"De Rips","A quas fuga dolorem voluptates reiciendis aperiam. Minus cupiditate autem modi repudiandae itaque laborum. Omnis et molestiae.","Facere aut ut nisi. Rerum voluptates minus dolore. Rem facere autem quo natus. Commodi magnam sed omnis. Iure vero enim et unde.
    ","De Rips","de-rips",1,"de-rips",NULL,"2015-07-08 12:31:12","2015-07-20 08:29:28","home-hero_itteren.jpg","image/jpeg",639836,"2015-07-08 12:37:26",1,51.555,5.80406
    267,"Marknesse","Ad cumque nisi. Incidunt porro voluptatem ut sint ut nobis. Modi aut adipisci est quia. Occaecati magnam ut fugit dolor delectus velit rerum.","Initiatiefnemer Bert van de Veen heeft met enkele enthouasiaste buurtgenoten het initiatief genomen om in Prinsenbeek energiebesparing op de kaart te zetten. En met succes! Maar we zijn er nog niet, want hoe meer buurtgenoten meedoen, hoe interessanter het wordt. Doe dus ook mee!
    ","Marknesse","marknesse",1,"marknesse",NULL,"2015-07-08 12:31:12","2015-07-28 08:44:52","home-hero_heesch.jpg","image/jpeg",533569,"2015-07-08 12:37:08",1,52.7073,5.86423
</textarea>



<script>   

var elem= $("#text").text();
var longlat= $.csv.toArrays(elem);

</script>

<script src="scripts/engine.js"></script>
</body>
</html>

